# Generated by Django 4.2.7 on 2023-12-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poststock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
