# Generated by Django 4.2.7 on 2023-12-25 07:53

from django.db import migrations, models
import poststock.models


class Migration(migrations.Migration):

    dependencies = [
        ('poststock', '0002_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=poststock.models.user_profile_image_upload_to),
        ),
    ]
